# Generated by Django 5.0.6 on 2024-05-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_Media_App', '0006_sharedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_on',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
