# Generated by Django 5.0.6 on 2024-06-03 04:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "Social_Media_App",
            "0010_remove_message_chat_rename_text_message_content_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="content",
            new_name="message",
        ),
    ]
