# Generated by Django 5.0.6 on 2024-06-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Social_Media_App", "0014_remove_customuser_otp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
