# Generated by Django 5.0.6 on 2024-06-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Social_Media_App", "0015_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
