# Generated by Django 5.0.6 on 2024-06-12 05:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_Media_App', '0018_customuser_blocked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
